server :
  port : 42308
  ssl:
    enabled: false
    key-store: "keystore.pkcs12"
    key-store-password: ezip
    keyStoreType: PKCS12

conversion:
  messaging :
    googlepubsub :
      project-id: tp-ezipeflix-ss
      topic-id: video-conversion-queue
  data:
    google:
      entity-name: video_conversion